### ISSUE TITLE
Creative Tabs in 1.12.1

### ISSUE THREAD

**Issue by Thiana** [CerulanLumina/HealthHungerTweaks#10]
In MC 1.12.1, HHT items are appearing in all creative tabs. This issue also appeared in McJty's OneProbe, the cause and commit with solution is available here: McJty/TheOneProbe/issues/169. Basically you need to check `this.isInCreativeTab(tab)` in `getSubItems()` before adding items to the tab.

Thanks.

**Comment by LuminaSapphira** [comment]
I think its fixed in e38d8c4. Uploading a build to Curse...
