### ISSUE TITLE
Friendly Request / Suggestion / Logic Improvement"

### ISSUE THREAD

**Issue by ghost** [CerulanLumina/HealthHungerTweaks#12]
hi. im using this mod for a while. i like it, and i have a suggestion for it, if you bother.

-new health regeneration system-(automatic)
health will regenerate with the speed by respect to hunger bars. 
how it works:
health will regenerate "1 hp/50 ticks" if the hunger bar is 20/20.
1 hp/60 ticks if hunger bar is 19/20
1 hp/70 ticks > hunger = 18/20...
continues regularly just like this.

thanks for reading or implementing this ! :)

**Comment by LuminaSapphira** [comment]
I like this suggestion, and may decide to implement it as a mode in the config. Thanks!

**Comment by ghost** [comment]
thanks. you can also play with that numbers for the greatest implementation/realistic regen. i just throwed that numbers(tick)
