### ISSUE TITLE
Suggestion regarding the hunger debuff, and its regards to satiation

### ISSUE THREAD

**Issue by Sunconure11** [CerulanLumina/HealthHungerTweaks#13]
On 1.12, can you make the hunger debuff automatically take out the satiated effect, if it is in place? Or at least, offer a config option?

**Comment by LuminaSapphira** [comment]
Yeah I'll look into it.

**Comment by Sunconure11** [comment]
Noticed this on 1.11.2, but I'm sure it persisted into 1.12.

**Comment by LuminaSapphira** [comment]
It'll be fixed in a future update, but I no longer support 1.11.2 so it will not come to that version unfortunately.

**Comment by LuminaSapphira** [comment]
Wow, its been over a year and a half. Code added to 3.0.0 branch to fix this.
