### ISSUE TITLE
Kicked to Main Menu

### ISSUE THREAD

**Issue by Mattabase** [CerulanLumina/HealthHungerTweaks#16]
You are kicked to the multplayer screen from a singleplayer world when you try to open the Health menu or when you try to use a health kit. 

This only happens on newer versions of forge (forge 2860) 

Full log
https://goo.gl/pG7zVK

Check line 5771 to see the error that occurs when I hit either key
or check this link
https://gist.github.com/Mattabase/a5fbf3f07fd4b43ade220169ddeb8303

**Comment by LuminaSapphira** [comment]
Thanks for the report, I'll check on this tomorrow.

**Comment by LuminaSapphira** [comment]
Uploading version 2.1.2 to Curse shortly, please try that when available! Thanks again for the report ^^
