### ISSUE TITLE
[Suggestion] Disable Health Kits

### ISSUE THREAD

**Issue by Mike-U5** [CerulanLumina/HealthHungerTweaks#17]
I like the FPS-style regeneration that this mod provides, but I am not very fond of the health kits.
Would you consider adding a config option to disable health kits, as well as the health kit interface.

**Comment by LuminaSapphira** [comment]
yeah, will do a soft-disable (disables registration of keybinds & recipes (if i can), prevents processing server-side as well). will be done in next major update

**Comment by LuminaSapphira** [comment]
I apologize for the delay, real life stuff happening and I was taking a hiatus from Minecraft. Feature to be added in 3.0.0
