### ISSUE TITLE
Disable for each functionality section

### ISSUE THREAD

**Issue by Palimon** [CerulanLumina/HealthHungerTweaks#19]
I'd like toggles for each major functionality of this mod so I can use it to only use the health packs.

I already have my regen completely tweaked using HungerOverhaul.  I love your health packs though!  I'm playing 1.10.2.

**Comment by LuminaSapphira** [comment]
Everything you're looking to do should be possible already (the Invasion modpack uses this mod solely for its screen tinting), what to do is as follows:
- Set `satiated.enableSatiated` to `false`
- Set `exhaustion.exhaustionModifier` to `1.0`
- Set `mending.disableRegularRegen` to `false`
- Set `client.screenDarken` to `false` *(This is just aesthetic, so you can keep it if you like it and it won't change any game mechanics)*

As a side note, I'm not actively working on 1.10 any more so if there is something you'd like to see happen that absolutely can't be done via the config, feel free to fork my repo and add it yourself (and maybe even send me a PR so I can maybe add it to the main mod too~)
