### ISSUE TITLE
Strange MiencraftServer Freez

### ISSUE THREAD

**Issue by SirAron111** [CerulanLumina/HealthHungerTweaks#20]
The World Freezes and you can’t do anything anymore just push around the mobs with your body but not attack them and nothing moves can’t even drop items but it isn’t a crash I have to use task manager to stop minecraft as I can’t do anything can this be fixed? The last thing the log tells m eis that health and hunger tweaks tried something.

Here is a link to the log of the console:
https://pastebin.com/W4t2MzHn

**Comment by LuminaSapphira** [comment]
Hi, thanks for the issue. The only thing I can find in that log file relating to Health and Hunger Tweaks is an undefined packet discriminator, which was fixed in the most recent version of HHT. Does it still occur when you use that version?

**Comment by SirAron111** [comment]
k doesnt seem to happen in the 
healthhungertweaks-1.12-2.1.2.jar
version but i had to manualy install it i coudltn automaticaly update to it on the twitch app
thx for the help

**Comment by LuminaSapphira** [comment]
No problem, glad that helped!
About the auto-update issue, it was likely due to the fact that I had forgotten to set that version to release after playtesting it for a week, as I had planned, and Twitch doesn't usually select Beta/Alpha versions.
