### ISSUE TITLE
Blank screen when messages in chat

### ISSUE THREAD

**Issue by lebanni** [CerulanLumina/HealthHungerTweaks#21]
forge-1.12.2-14.23.5.2814-universal.jar
OptiFine_1.12.2_HD_U_E3.jar
healthhungertweaks-1.12-2.1.2.jar

The screen goes white when messages are displayed in the chat. Back to normal when messages fade away.
Also no white screen when the inventory or a block is open.

**Comment by LuminaSapphira** [comment]
Are there any other mods installed?
Also, does this occur in multiplayer and singleplayer?

Edit: I cannot confirm with just these mods in singleplayer, could you post the full modlist and exactly when/where it occurs, as well as your optifine settings? (your options.txt and optionsof.txt will be fine)

**Comment by lebanni** [comment]
[server_modlist.txt](https://github.com/CerulanLumina/HealthHungerTweaks/files/2896927/server_modlist.txt)
[client_modlist.txt](https://github.com/CerulanLumina/HealthHungerTweaks/files/2896928/client_modlist.txt)
[options.txt](https://github.com/CerulanLumina/HealthHungerTweaks/files/2896929/options.txt)
[optionsof.txt](https://github.com/CerulanLumina/HealthHungerTweaks/files/2896930/optionsof.txt)

**Comment by LuminaSapphira** [comment]
Alright I went through and debugged this mod list for you, its a bug with BaublesHud - https://github.com/gigabit101/BaublesHud/issues/8. It effects other mod's rendering because of incorrect rendering during the RenderGameOverlayEvent. I suggest you take it up with the developer of that mod.
