### ISSUE TITLE
Latest 3.0.0 beta crashes server

### ISSUE THREAD

**Issue by Lyokanthrope** [CerulanLumina/HealthHungerTweaks#23]
Crash report from server: https://gist.github.com/Lyokanthrope/3afec5a6b8b730c9859ffc5896f5a9ad

Small self-made modpack with friends, added this due to some complaints about Minecraft's god awful default hunger system. Unfortunately, it causes a crash when enabled. Server boots fine without it.

**Comment by LuminaSapphira** [comment]
Thanks for the report, looks like I forgot a SideOnly annotation and then further forgot to test on dedicated servers before releasing the beta. 3.0.1 is on Curse now which should fix this issue. Let me know if you find any more!
