### ISSUE TITLE
1.11.2 Port?

### ISSUE THREAD

**Issue by Thiana** [CerulanLumina/HealthHungerTweaks#7]
Will you be updating HHT for 1.11.2? Thanks.

**Comment by LuminaSapphira** [comment]
I will be updating it for 1.11.2 :) . However, I am a little busy right now with life things, so it may be a couple weeks or so.

**Comment by LuminaSapphira** [comment]
Sorry for the extended delay. A 1.11.2 port should be up on CurseForge now.
