### ISSUE TITLE
instant crash when eating food

### ISSUE THREAD

**Issue by EchenCraft** [CerulanLumina/HealthHungerTweaks#8]
Im sure thiss is a conflict with something else but not sure what.

Eat anything, instant crash

https://pastebin.com/9wmmMSyw

**Comment by LuminaSapphira** [comment]
Thank you for the crash report. Unfortunately I am unable to reproduce with just HHT (and AppleCore) installed, so I am also of the opinion that there is a conflict with another mod. If you are using a modpack, could you link the pack?

Thanks~

**Comment by EchenCraft** [comment]
Its a WIP we are working on

here is the current build of it that has the issue

[Mod Pack](https://github.com/EchenCraft/Darklight)

as soon as I get a chance, If you havent narrowed it down by then Ill start dissabling mods and try to narrow it down I just didnt have time atm, we were testing other things when I ate a piece of flesh and crashed and then duped the crash with an apple.

alot has changed with the pack since the last time I tried eating something so Im completely uncertain which mod HHT isnt likeing .... and their are quite a few mods affecting health that I thought I had balanced out :(

**Comment by EchenCraft** [comment]
Fixed the issue but still unsure what the exact cause was.

I disabled Hardcore Hunger in the config for Better with mods, However it isnt just better with mods involved.

I literally spent about 10 hours straight trying to figure out what the combination of mods causing it was but couldnt narrow it down, I started disabling mods 1 at a time stating with "A" when the obvious things didnt pan out any results. 

got to the "R's"  and all of a sudden it stopped crashing when eating.... so it had to be the last mod in the R's right? no.... after re-enabling the last mod disabled... it didnt crash when the expected result was to crash. enabled them all the way back to the L's still without crashing.... I gave up at that point and started reevaluating my configs, after noticing an issue with being unable to place logs on a chopping block (Survivalist) I found the cause of that was with better with mods. in that config noticed the line Hardcore Hunger..... went back to see what that did and it apparently completely changes the hunger system. I disabled it and I could eat without crashing again with all of the mods enabled.

So it appears that better with mods has alot to do with it however..... it cant be reproduced with ONLY HHT, applecore, and Better with mods....... something else is involved.

I can only suggest to anyone else with this isssue at this time that has these 3 mods installed should disable hardcore hunger in the better with mods config.

Ive never had so much trouble narrowing down a combination like this :/

**Comment by LuminaSapphira** [comment]
Sorry for the silence, finals have been hectic. I'm looking into implementing a null check on the offending line, but it shouldn't be necessary as it *shouldn't* ever be null. At least it will stop the crashing, but it won't solve the issue.

And yeah, I once had an issue involving a crash if and only if three mods were installed together. It sucks.

**Comment by EchenCraft** [comment]
I've never had an issue narrowing down the exact combo and being able to dupe the problem. It completely blew my mind when all of a sudden it started working properlly and then continued to do so after re-enabling mods that it previously was crashing with. In this pack there are a number of mods that affect health, food and hunger so tracking it down I knew would be a problem but at this point I'm inclined to believe the missing piece of the puzzle is a library used by a mod that doesn't actually affect those things... as in the library itself contains code that is interfering even though the dependant mod doesn't utilize that.
